[theme]
primaryColor = "#00f0ff"          # Neon cyaan voor actieve selecties
backgroundColor = "#0d0b18"       # Deep space heel donkerpaars
secondaryBackgroundColor = "#1b1532" # Iets lichter paars voor de Sidebar
textColor = "#ffffff"             # Wit voor perfect leesbare tekst
font = "sans serif"               # Strak en modern leesbaar
