[theme]
primaryColor = "#70d6ff"          # Helder, zacht hemelsblauw voor actieve selecties
backgroundColor = "#0f1123"       # Diep, mysterieus indigo-blauw (als een heldere nacht)
secondaryBackgroundColor = "#181b35" # Iets lichter indigo voor de Sidebar
textColor = "#ffffff"             # Wit voor perfect leesbare tekst
font = "sans serif"               # Strak en modern leesbaar
